//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PirateJobBoard.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenAssignment()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int OpenAssignmentID { get; set; }
        public int AssignmentID { get; set; }
        public int ShipID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
