//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PirateJobBoard.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.OpenAssignments = new HashSet<OpenAssignment>();
        }
    
        public int ShipID { get; set; }
        public string ShipName { get; set; }
        public string HomePort { get; set; }
        public string CaptainID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenAssignment> OpenAssignments { get; set; }
        public virtual PirateDetail PirateDetail { get; set; }
    }
}
